/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "./src/context"



declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFieldUpdateOperationsInput: { // input type
    set?: boolean | null; // Boolean
  }
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  FileCreateManyTaskInput: { // input type
    id?: number | null; // Int
    name: string; // String!
    url: string; // String!
  }
  FileCreateManyTaskInputEnvelope: { // input type
    data?: NexusGenInputs['FileCreateManyTaskInput'][] | null; // [FileCreateManyTaskInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  FileCreateNestedManyWithoutTaskInput: { // input type
    connect?: NexusGenInputs['FileWhereUniqueInput'][] | null; // [FileWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['FileCreateOrConnectWithoutTaskInput'][] | null; // [FileCreateOrConnectWithoutTaskInput!]
    create?: NexusGenInputs['FileCreateWithoutTaskInput'][] | null; // [FileCreateWithoutTaskInput!]
    createMany?: NexusGenInputs['FileCreateManyTaskInputEnvelope'] | null; // FileCreateManyTaskInputEnvelope
  }
  FileCreateOrConnectWithoutTaskInput: { // input type
    create: NexusGenInputs['FileCreateWithoutTaskInput']; // FileCreateWithoutTaskInput!
    where: NexusGenInputs['FileWhereUniqueInput']; // FileWhereUniqueInput!
  }
  FileCreateWithoutTaskInput: { // input type
    name: string; // String!
    url: string; // String!
  }
  FileScalarWhereInput: { // input type
    AND?: NexusGenInputs['FileScalarWhereInput'][] | null; // [FileScalarWhereInput!]
    NOT?: NexusGenInputs['FileScalarWhereInput'][] | null; // [FileScalarWhereInput!]
    OR?: NexusGenInputs['FileScalarWhereInput'][] | null; // [FileScalarWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    taskId?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    url?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  FileUpdateManyMutationInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    url?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  FileUpdateManyWithWhereWithoutTaskInput: { // input type
    data: NexusGenInputs['FileUpdateManyMutationInput']; // FileUpdateManyMutationInput!
    where: NexusGenInputs['FileScalarWhereInput']; // FileScalarWhereInput!
  }
  FileUpdateManyWithoutTaskInput: { // input type
    connect?: NexusGenInputs['FileWhereUniqueInput'][] | null; // [FileWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['FileCreateOrConnectWithoutTaskInput'][] | null; // [FileCreateOrConnectWithoutTaskInput!]
    create?: NexusGenInputs['FileCreateWithoutTaskInput'][] | null; // [FileCreateWithoutTaskInput!]
    createMany?: NexusGenInputs['FileCreateManyTaskInputEnvelope'] | null; // FileCreateManyTaskInputEnvelope
    delete?: NexusGenInputs['FileWhereUniqueInput'][] | null; // [FileWhereUniqueInput!]
    deleteMany?: NexusGenInputs['FileScalarWhereInput'][] | null; // [FileScalarWhereInput!]
    disconnect?: NexusGenInputs['FileWhereUniqueInput'][] | null; // [FileWhereUniqueInput!]
    set?: NexusGenInputs['FileWhereUniqueInput'][] | null; // [FileWhereUniqueInput!]
    update?: NexusGenInputs['FileUpdateWithWhereUniqueWithoutTaskInput'][] | null; // [FileUpdateWithWhereUniqueWithoutTaskInput!]
    updateMany?: NexusGenInputs['FileUpdateManyWithWhereWithoutTaskInput'][] | null; // [FileUpdateManyWithWhereWithoutTaskInput!]
    upsert?: NexusGenInputs['FileUpsertWithWhereUniqueWithoutTaskInput'][] | null; // [FileUpsertWithWhereUniqueWithoutTaskInput!]
  }
  FileUpdateWithWhereUniqueWithoutTaskInput: { // input type
    data: NexusGenInputs['FileUpdateWithoutTaskInput']; // FileUpdateWithoutTaskInput!
    where: NexusGenInputs['FileWhereUniqueInput']; // FileWhereUniqueInput!
  }
  FileUpdateWithoutTaskInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    url?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  FileUpsertWithWhereUniqueWithoutTaskInput: { // input type
    create: NexusGenInputs['FileCreateWithoutTaskInput']; // FileCreateWithoutTaskInput!
    update: NexusGenInputs['FileUpdateWithoutTaskInput']; // FileUpdateWithoutTaskInput!
    where: NexusGenInputs['FileWhereUniqueInput']; // FileWhereUniqueInput!
  }
  FileWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  IntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ProjectCreateInput: { // input type
    avatars?: NexusGenInputs['ProjectCreateavatarsInput'] | null; // ProjectCreateavatarsInput
    className: string; // String!
    logo: string; // String!
    name: string; // String!
    tasks?: NexusGenInputs['TaskCreateNestedManyWithoutProjectInput'] | null; // TaskCreateNestedManyWithoutProjectInput
  }
  ProjectCreateNestedOneWithoutTasksInput: { // input type
    connect?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProjectCreateOrConnectWithoutTasksInput'] | null; // ProjectCreateOrConnectWithoutTasksInput
    create?: NexusGenInputs['ProjectCreateWithoutTasksInput'] | null; // ProjectCreateWithoutTasksInput
  }
  ProjectCreateOrConnectWithoutTasksInput: { // input type
    create: NexusGenInputs['ProjectCreateWithoutTasksInput']; // ProjectCreateWithoutTasksInput!
    where: NexusGenInputs['ProjectWhereUniqueInput']; // ProjectWhereUniqueInput!
  }
  ProjectCreateWithoutTasksInput: { // input type
    avatars?: NexusGenInputs['ProjectCreateavatarsInput'] | null; // ProjectCreateavatarsInput
    className: string; // String!
    logo: string; // String!
    name: string; // String!
  }
  ProjectCreateavatarsInput: { // input type
    set?: string[] | null; // [String!]
  }
  ProjectUpdateOneRequiredWithoutTasksInput: { // input type
    connect?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProjectCreateOrConnectWithoutTasksInput'] | null; // ProjectCreateOrConnectWithoutTasksInput
    create?: NexusGenInputs['ProjectCreateWithoutTasksInput'] | null; // ProjectCreateWithoutTasksInput
    update?: NexusGenInputs['ProjectUpdateWithoutTasksInput'] | null; // ProjectUpdateWithoutTasksInput
    upsert?: NexusGenInputs['ProjectUpsertWithoutTasksInput'] | null; // ProjectUpsertWithoutTasksInput
  }
  ProjectUpdateWithoutTasksInput: { // input type
    avatars?: NexusGenInputs['ProjectUpdateavatarsInput'] | null; // ProjectUpdateavatarsInput
    className?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    logo?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProjectUpdateavatarsInput: { // input type
    push?: string | null; // String
    set?: string[] | null; // [String!]
  }
  ProjectUpsertWithoutTasksInput: { // input type
    create: NexusGenInputs['ProjectCreateWithoutTasksInput']; // ProjectCreateWithoutTasksInput!
    update: NexusGenInputs['ProjectUpdateWithoutTasksInput']; // ProjectUpdateWithoutTasksInput!
  }
  ProjectWhereUniqueInput: { // input type
    id?: number | null; // Int
    name?: string | null; // String
  }
  QuickTaskCreateInput: { // input type
    description: string; // String!
    done?: boolean | null; // Boolean
  }
  QuickTaskUpdateInput: { // input type
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    done?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
  }
  QuickTaskWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  ScheduledTaskCreateInput: { // input type
    datetime: NexusGenScalars['DateTime']; // DateTime!
    done?: boolean | null; // Boolean
    order: number; // Int!
    section: number; // Int!
    task: NexusGenInputs['TaskCreateNestedOneWithoutScheduledTaskInput']; // TaskCreateNestedOneWithoutScheduledTaskInput!
  }
  ScheduledTaskCreateManyTaskInput: { // input type
    datetime: NexusGenScalars['DateTime']; // DateTime!
    done?: boolean | null; // Boolean
    id?: number | null; // Int
    order: number; // Int!
    section: number; // Int!
  }
  ScheduledTaskCreateManyTaskInputEnvelope: { // input type
    data?: NexusGenInputs['ScheduledTaskCreateManyTaskInput'][] | null; // [ScheduledTaskCreateManyTaskInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  ScheduledTaskCreateNestedManyWithoutTaskInput: { // input type
    connect?: NexusGenInputs['ScheduledTaskWhereUniqueInput'][] | null; // [ScheduledTaskWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ScheduledTaskCreateOrConnectWithoutTaskInput'][] | null; // [ScheduledTaskCreateOrConnectWithoutTaskInput!]
    create?: NexusGenInputs['ScheduledTaskCreateWithoutTaskInput'][] | null; // [ScheduledTaskCreateWithoutTaskInput!]
    createMany?: NexusGenInputs['ScheduledTaskCreateManyTaskInputEnvelope'] | null; // ScheduledTaskCreateManyTaskInputEnvelope
  }
  ScheduledTaskCreateOrConnectWithoutTaskInput: { // input type
    create: NexusGenInputs['ScheduledTaskCreateWithoutTaskInput']; // ScheduledTaskCreateWithoutTaskInput!
    where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
  }
  ScheduledTaskCreateWithoutTaskInput: { // input type
    datetime: NexusGenScalars['DateTime']; // DateTime!
    done?: boolean | null; // Boolean
    order: number; // Int!
    section: number; // Int!
  }
  ScheduledTaskScalarWhereInput: { // input type
    AND?: NexusGenInputs['ScheduledTaskScalarWhereInput'][] | null; // [ScheduledTaskScalarWhereInput!]
    NOT?: NexusGenInputs['ScheduledTaskScalarWhereInput'][] | null; // [ScheduledTaskScalarWhereInput!]
    OR?: NexusGenInputs['ScheduledTaskScalarWhereInput'][] | null; // [ScheduledTaskScalarWhereInput!]
    datetime?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    done?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    order?: NexusGenInputs['IntFilter'] | null; // IntFilter
    section?: NexusGenInputs['IntFilter'] | null; // IntFilter
    taskId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ScheduledTaskUpdateInput: { // input type
    datetime?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    done?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    order?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    section?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    task?: NexusGenInputs['TaskUpdateOneRequiredWithoutScheduledTaskInput'] | null; // TaskUpdateOneRequiredWithoutScheduledTaskInput
  }
  ScheduledTaskUpdateManyMutationInput: { // input type
    datetime?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    done?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    order?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    section?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  ScheduledTaskUpdateManyWithWhereWithoutTaskInput: { // input type
    data: NexusGenInputs['ScheduledTaskUpdateManyMutationInput']; // ScheduledTaskUpdateManyMutationInput!
    where: NexusGenInputs['ScheduledTaskScalarWhereInput']; // ScheduledTaskScalarWhereInput!
  }
  ScheduledTaskUpdateManyWithoutTaskInput: { // input type
    connect?: NexusGenInputs['ScheduledTaskWhereUniqueInput'][] | null; // [ScheduledTaskWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ScheduledTaskCreateOrConnectWithoutTaskInput'][] | null; // [ScheduledTaskCreateOrConnectWithoutTaskInput!]
    create?: NexusGenInputs['ScheduledTaskCreateWithoutTaskInput'][] | null; // [ScheduledTaskCreateWithoutTaskInput!]
    createMany?: NexusGenInputs['ScheduledTaskCreateManyTaskInputEnvelope'] | null; // ScheduledTaskCreateManyTaskInputEnvelope
    delete?: NexusGenInputs['ScheduledTaskWhereUniqueInput'][] | null; // [ScheduledTaskWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ScheduledTaskScalarWhereInput'][] | null; // [ScheduledTaskScalarWhereInput!]
    disconnect?: NexusGenInputs['ScheduledTaskWhereUniqueInput'][] | null; // [ScheduledTaskWhereUniqueInput!]
    set?: NexusGenInputs['ScheduledTaskWhereUniqueInput'][] | null; // [ScheduledTaskWhereUniqueInput!]
    update?: NexusGenInputs['ScheduledTaskUpdateWithWhereUniqueWithoutTaskInput'][] | null; // [ScheduledTaskUpdateWithWhereUniqueWithoutTaskInput!]
    updateMany?: NexusGenInputs['ScheduledTaskUpdateManyWithWhereWithoutTaskInput'][] | null; // [ScheduledTaskUpdateManyWithWhereWithoutTaskInput!]
    upsert?: NexusGenInputs['ScheduledTaskUpsertWithWhereUniqueWithoutTaskInput'][] | null; // [ScheduledTaskUpsertWithWhereUniqueWithoutTaskInput!]
  }
  ScheduledTaskUpdateWithWhereUniqueWithoutTaskInput: { // input type
    data: NexusGenInputs['ScheduledTaskUpdateWithoutTaskInput']; // ScheduledTaskUpdateWithoutTaskInput!
    where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
  }
  ScheduledTaskUpdateWithoutTaskInput: { // input type
    datetime?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    done?: NexusGenInputs['BoolFieldUpdateOperationsInput'] | null; // BoolFieldUpdateOperationsInput
    order?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
    section?: NexusGenInputs['IntFieldUpdateOperationsInput'] | null; // IntFieldUpdateOperationsInput
  }
  ScheduledTaskUpsertWithWhereUniqueWithoutTaskInput: { // input type
    create: NexusGenInputs['ScheduledTaskCreateWithoutTaskInput']; // ScheduledTaskCreateWithoutTaskInput!
    update: NexusGenInputs['ScheduledTaskUpdateWithoutTaskInput']; // ScheduledTaskUpdateWithoutTaskInput!
    where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
  }
  ScheduledTaskWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  TaskCreateInput: { // input type
    ScheduledTask?: NexusGenInputs['ScheduledTaskCreateNestedManyWithoutTaskInput'] | null; // ScheduledTaskCreateNestedManyWithoutTaskInput
    description: string; // String!
    files?: NexusGenInputs['FileCreateNestedManyWithoutTaskInput'] | null; // FileCreateNestedManyWithoutTaskInput
    project: NexusGenInputs['ProjectCreateNestedOneWithoutTasksInput']; // ProjectCreateNestedOneWithoutTasksInput!
    title: string; // String!
  }
  TaskCreateManyProjectInput: { // input type
    description: string; // String!
    id?: number | null; // Int
    title: string; // String!
  }
  TaskCreateManyProjectInputEnvelope: { // input type
    data?: NexusGenInputs['TaskCreateManyProjectInput'][] | null; // [TaskCreateManyProjectInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  TaskCreateNestedManyWithoutProjectInput: { // input type
    connect?: NexusGenInputs['TaskWhereUniqueInput'][] | null; // [TaskWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TaskCreateOrConnectWithoutProjectInput'][] | null; // [TaskCreateOrConnectWithoutProjectInput!]
    create?: NexusGenInputs['TaskCreateWithoutProjectInput'][] | null; // [TaskCreateWithoutProjectInput!]
    createMany?: NexusGenInputs['TaskCreateManyProjectInputEnvelope'] | null; // TaskCreateManyProjectInputEnvelope
  }
  TaskCreateNestedOneWithoutScheduledTaskInput: { // input type
    connect?: NexusGenInputs['TaskWhereUniqueInput'] | null; // TaskWhereUniqueInput
    connectOrCreate?: NexusGenInputs['TaskCreateOrConnectWithoutScheduledTaskInput'] | null; // TaskCreateOrConnectWithoutScheduledTaskInput
    create?: NexusGenInputs['TaskCreateWithoutScheduledTaskInput'] | null; // TaskCreateWithoutScheduledTaskInput
  }
  TaskCreateOrConnectWithoutProjectInput: { // input type
    create: NexusGenInputs['TaskCreateWithoutProjectInput']; // TaskCreateWithoutProjectInput!
    where: NexusGenInputs['TaskWhereUniqueInput']; // TaskWhereUniqueInput!
  }
  TaskCreateOrConnectWithoutScheduledTaskInput: { // input type
    create: NexusGenInputs['TaskCreateWithoutScheduledTaskInput']; // TaskCreateWithoutScheduledTaskInput!
    where: NexusGenInputs['TaskWhereUniqueInput']; // TaskWhereUniqueInput!
  }
  TaskCreateWithoutProjectInput: { // input type
    ScheduledTask?: NexusGenInputs['ScheduledTaskCreateNestedManyWithoutTaskInput'] | null; // ScheduledTaskCreateNestedManyWithoutTaskInput
    description: string; // String!
    files?: NexusGenInputs['FileCreateNestedManyWithoutTaskInput'] | null; // FileCreateNestedManyWithoutTaskInput
    title: string; // String!
  }
  TaskCreateWithoutScheduledTaskInput: { // input type
    description: string; // String!
    files?: NexusGenInputs['FileCreateNestedManyWithoutTaskInput'] | null; // FileCreateNestedManyWithoutTaskInput
    project: NexusGenInputs['ProjectCreateNestedOneWithoutTasksInput']; // ProjectCreateNestedOneWithoutTasksInput!
    title: string; // String!
  }
  TaskUpdateInput: { // input type
    ScheduledTask?: NexusGenInputs['ScheduledTaskUpdateManyWithoutTaskInput'] | null; // ScheduledTaskUpdateManyWithoutTaskInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    files?: NexusGenInputs['FileUpdateManyWithoutTaskInput'] | null; // FileUpdateManyWithoutTaskInput
    project?: NexusGenInputs['ProjectUpdateOneRequiredWithoutTasksInput'] | null; // ProjectUpdateOneRequiredWithoutTasksInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TaskUpdateOneRequiredWithoutScheduledTaskInput: { // input type
    connect?: NexusGenInputs['TaskWhereUniqueInput'] | null; // TaskWhereUniqueInput
    connectOrCreate?: NexusGenInputs['TaskCreateOrConnectWithoutScheduledTaskInput'] | null; // TaskCreateOrConnectWithoutScheduledTaskInput
    create?: NexusGenInputs['TaskCreateWithoutScheduledTaskInput'] | null; // TaskCreateWithoutScheduledTaskInput
    update?: NexusGenInputs['TaskUpdateWithoutScheduledTaskInput'] | null; // TaskUpdateWithoutScheduledTaskInput
    upsert?: NexusGenInputs['TaskUpsertWithoutScheduledTaskInput'] | null; // TaskUpsertWithoutScheduledTaskInput
  }
  TaskUpdateWithoutScheduledTaskInput: { // input type
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    files?: NexusGenInputs['FileUpdateManyWithoutTaskInput'] | null; // FileUpdateManyWithoutTaskInput
    project?: NexusGenInputs['ProjectUpdateOneRequiredWithoutTasksInput'] | null; // ProjectUpdateOneRequiredWithoutTasksInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TaskUpsertWithoutScheduledTaskInput: { // input type
    create: NexusGenInputs['TaskCreateWithoutScheduledTaskInput']; // TaskCreateWithoutScheduledTaskInput!
    update: NexusGenInputs['TaskUpdateWithoutScheduledTaskInput']; // TaskUpdateWithoutScheduledTaskInput!
  }
  TaskWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Mutation: {};
  Project: { // root type
    avatars: string[]; // [String!]!
    className: string; // String!
    id: number; // Int!
    logo: string; // String!
    name: string; // String!
  }
  Query: {};
  QuickTask: { // root type
    description?: string | null; // String
    done?: boolean | null; // Boolean
    id?: number | null; // Int
  }
  ScheduledTask: { // root type
    datetime?: string | null; // String
    done?: boolean | null; // Boolean
    id?: number | null; // Int
    order?: number | null; // Int
    section?: number | null; // Int
    taskId?: number | null; // Int
  }
  Task: { // root type
    description?: string | null; // String
    id?: number | null; // Int
    projectId?: number | null; // Int
    title?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOneProject: NexusGenRootTypes['Project']; // Project!
    createOneQuickTask: NexusGenRootTypes['QuickTask']; // QuickTask!
    createOneScheduledTask: NexusGenRootTypes['ScheduledTask']; // ScheduledTask!
    createOneTask: NexusGenRootTypes['Task']; // Task!
    deleteManyQuickTask: NexusGenRootTypes['QuickTask'] | null; // QuickTask
    deleteOneQuickTask: NexusGenRootTypes['QuickTask'] | null; // QuickTask
    deleteOneScheduledTask: NexusGenRootTypes['ScheduledTask'] | null; // ScheduledTask
    deleteOneTask: NexusGenRootTypes['Task'] | null; // Task
    updateOneQuickTask: NexusGenRootTypes['QuickTask'] | null; // QuickTask
    updateOneScheduledTask: NexusGenRootTypes['ScheduledTask'] | null; // ScheduledTask
    updateOneTask: NexusGenRootTypes['Task'] | null; // Task
  }
  Project: { // field return type
    avatars: string[]; // [String!]!
    className: string; // String!
    id: number; // Int!
    logo: string; // String!
    name: string; // String!
    tasks: NexusGenRootTypes['Task'][]; // [Task!]!
  }
  Query: { // field return type
    project: NexusGenRootTypes['Project'] | null; // Project
    projects: NexusGenRootTypes['Project'][]; // [Project!]!
    quickTask: NexusGenRootTypes['QuickTask'] | null; // QuickTask
    quickTasks: NexusGenRootTypes['QuickTask'][]; // [QuickTask!]!
    scheduledTask: NexusGenRootTypes['ScheduledTask'] | null; // ScheduledTask
    scheduledTasks: NexusGenRootTypes['ScheduledTask'][]; // [ScheduledTask!]!
    task: NexusGenRootTypes['Task'] | null; // Task
    tasks: NexusGenRootTypes['Task'][]; // [Task!]!
  }
  QuickTask: { // field return type
    description: string | null; // String
    done: boolean | null; // Boolean
    id: number | null; // Int
  }
  ScheduledTask: { // field return type
    datetime: string | null; // String
    done: boolean | null; // Boolean
    id: number | null; // Int
    order: number | null; // Int
    section: number | null; // Int
    task: NexusGenRootTypes['Task'] | null; // Task
    taskId: number | null; // Int
  }
  Task: { // field return type
    description: string | null; // String
    id: number | null; // Int
    project: NexusGenRootTypes['Project'] | null; // Project
    projectId: number | null; // Int
    title: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createOneProject: 'Project'
    createOneQuickTask: 'QuickTask'
    createOneScheduledTask: 'ScheduledTask'
    createOneTask: 'Task'
    deleteManyQuickTask: 'QuickTask'
    deleteOneQuickTask: 'QuickTask'
    deleteOneScheduledTask: 'ScheduledTask'
    deleteOneTask: 'Task'
    updateOneQuickTask: 'QuickTask'
    updateOneScheduledTask: 'ScheduledTask'
    updateOneTask: 'Task'
  }
  Project: { // field return type name
    avatars: 'String'
    className: 'String'
    id: 'Int'
    logo: 'String'
    name: 'String'
    tasks: 'Task'
  }
  Query: { // field return type name
    project: 'Project'
    projects: 'Project'
    quickTask: 'QuickTask'
    quickTasks: 'QuickTask'
    scheduledTask: 'ScheduledTask'
    scheduledTasks: 'ScheduledTask'
    task: 'Task'
    tasks: 'Task'
  }
  QuickTask: { // field return type name
    description: 'String'
    done: 'Boolean'
    id: 'Int'
  }
  ScheduledTask: { // field return type name
    datetime: 'String'
    done: 'Boolean'
    id: 'Int'
    order: 'Int'
    section: 'Int'
    task: 'Task'
    taskId: 'Int'
  }
  Task: { // field return type name
    description: 'String'
    id: 'Int'
    project: 'Project'
    projectId: 'Int'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneProject: { // args
      data: NexusGenInputs['ProjectCreateInput']; // ProjectCreateInput!
    }
    createOneQuickTask: { // args
      data: NexusGenInputs['QuickTaskCreateInput']; // QuickTaskCreateInput!
    }
    createOneScheduledTask: { // args
      data: NexusGenInputs['ScheduledTaskCreateInput']; // ScheduledTaskCreateInput!
    }
    createOneTask: { // args
      data: NexusGenInputs['TaskCreateInput']; // TaskCreateInput!
    }
    deleteOneQuickTask: { // args
      where: NexusGenInputs['QuickTaskWhereUniqueInput']; // QuickTaskWhereUniqueInput!
    }
    deleteOneScheduledTask: { // args
      where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
    }
    deleteOneTask: { // args
      where: NexusGenInputs['TaskWhereUniqueInput']; // TaskWhereUniqueInput!
    }
    updateOneQuickTask: { // args
      data: NexusGenInputs['QuickTaskUpdateInput']; // QuickTaskUpdateInput!
      where: NexusGenInputs['QuickTaskWhereUniqueInput']; // QuickTaskWhereUniqueInput!
    }
    updateOneScheduledTask: { // args
      data: NexusGenInputs['ScheduledTaskUpdateInput']; // ScheduledTaskUpdateInput!
      where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
    }
    updateOneTask: { // args
      data: NexusGenInputs['TaskUpdateInput']; // TaskUpdateInput!
      where: NexusGenInputs['TaskWhereUniqueInput']; // TaskWhereUniqueInput!
    }
  }
  Query: {
    project: { // args
      where: NexusGenInputs['ProjectWhereUniqueInput']; // ProjectWhereUniqueInput!
    }
    projects: { // args
      after?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
      before?: NexusGenInputs['ProjectWhereUniqueInput'] | null; // ProjectWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    quickTask: { // args
      where: NexusGenInputs['QuickTaskWhereUniqueInput']; // QuickTaskWhereUniqueInput!
    }
    quickTasks: { // args
      after?: NexusGenInputs['QuickTaskWhereUniqueInput'] | null; // QuickTaskWhereUniqueInput
      before?: NexusGenInputs['QuickTaskWhereUniqueInput'] | null; // QuickTaskWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    scheduledTask: { // args
      where: NexusGenInputs['ScheduledTaskWhereUniqueInput']; // ScheduledTaskWhereUniqueInput!
    }
    scheduledTasks: { // args
      after?: NexusGenInputs['ScheduledTaskWhereUniqueInput'] | null; // ScheduledTaskWhereUniqueInput
      before?: NexusGenInputs['ScheduledTaskWhereUniqueInput'] | null; // ScheduledTaskWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    task: { // args
      where: NexusGenInputs['TaskWhereUniqueInput']; // TaskWhereUniqueInput!
    }
    tasks: { // args
      after?: NexusGenInputs['TaskWhereUniqueInput'] | null; // TaskWhereUniqueInput
      before?: NexusGenInputs['TaskWhereUniqueInput'] | null; // TaskWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
}